version: '3'

services:

  modelstore:
    container_name: modelstore_api
    restart: always
    build: ./modelstore
    image: genome-modelstore:development
    networks:
      - apinetwork
    expose:
      - "3000"
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 500M


  routing:
    container_name: routing_api
    restart: always
    build: ./routing
    image: genome-routing:development
    networks:
      - apinetwork
    expose:
      - "3003"
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MODELSTORE=http://modelstore:3000

    deploy:
      resources:
        limits:
          memory: 500M


  scoring:
    container_name: scoring_api
    restart: always
    build: ./scoring
    image: genome-scoring:development
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - MODELSTORE=http://modelstore:3000
    deploy:
      resources:
        limits:
          memory: 20G


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  apinetwork:
