apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "genome.fullname" . }}-elastic-validation-configmap
  namespace: "{{ .Values.environment }}"
  labels:
    app: {{ template "genome.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.elastic.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
  config: |
{{ .Files.Get "validationArtifactIndex.json" | indent 4 }}
