apiVersion: v1
kind: Secret
metadata:
  name: {{ template "genome.fullname" . }}-modelstore-pass
  namespace: "{{ .Values.environment }}"
type: Opaque
stringData:
    providerPass: "change-this-via-kubectl"
