apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "genome.fullname" . }}-configmap
  namespace: "{{ .Values.environment }}"
  labels:
    app: {{ template "genome.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.nginx.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:

  default.conf: |

      server {

          listen 8080;
          server_name modelstore.*;

          charset utf-8;
          client_max_body_size 150M;
          keepalive_timeout  360s;

          location /static/ {
              proxy_pass  http://{{ template "genome.fullname" . }}-modelstore-service:3000/static/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }

          location /v1.0/genome/modelstore/ {
              proxy_pass  http://{{ template "genome.fullname" . }}-modelstore-service:3000/v1.0/genome/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }

          location /v1.0/genome/routing/ {
              proxy_pass http://{{ template "genome.fullname" . }}-routing-service:3000/v1.0/genome/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_connect_timeout       300;
              proxy_send_timeout          300;
              proxy_read_timeout          600;
              send_timeout                300;
          }
      }
