apiVersion: v1
kind: Service
metadata:
  name: {{ template "genome.fullname" . }}-visualizer-service
  namespace: "{{ .Values.environment }}"
  labels:
    app: {{ template "genome.fullname" . }}
    chart: {{ template "genome.chart" . }}
    component: "{{ .Values.visualizer.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: {{ template "genome.fullname" . }}
    component: "{{ .Values.visualizer.name }}"
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
