# Default values for node-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: development

nginx:
  name: nginx
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    nodePort: 30000

modelstore:
  name: modelstore
  image:
    repository: genome-modelstore
    tag: development
    pullPolicy: IfNotPresent

routing:
  name: routing
  image:
    repository: genome-routing
    tag: development
    pullPolicy: IfNotPresent

scoring:
  name: scoring
  image:
    repository: genome-scoring
    tag: development
    pullPolicy: IfNotPresent
