# Default values for node-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: genesis

volumes:
  jsFolder:
  mntFolder:
  mntType:

nginx:
  name: nginx
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    nodePort: 30000

sidecar:
  name: sidecar
  image:
    repository: us-west1-docker.pkg.dev/genome-285119/genome/sidecar-kubectl
    tag: latest
    pullPolicy: IfNotPresent

index_cronjob:
  name: index_cronjob
  image:
    repository: curlimages/curl
    tag: latest
    pullPolicy: IfNotPresent

modelstore:
  name: modelstore
  image:
    repository: us-west1-docker.pkg.dev/genome-285119/genome/genome-modelstore
    tag: development
    pullPolicy: IfNotPresent

routing:
  name: routing
  image:
    repository: us-west1-docker.pkg.dev/genome-285119/genome/genome-routing
    tag: development
    pullPolicy: IfNotPresent

compute:
  name: compute
  image:
    repository: us-west1-docker.pkg.dev/genome-285119/genome/genome-compute
    tag: development
    pullPolicy: IfNotPresent

scoring:
  name: scoring
  image:
    repository: us-west1-docker.pkg.dev/genome-285119/genome/genome-scoring
    tag: development
    pullPolicy: IfNotPresent

visualizer:
  name: visualizer
  image:
    repository: us-west1-docker.pkg.dev/genome-285119/genome/genome-visualizer
    tag: development
    pullPolicy: IfNotPresent

elastic:
  name: elastic
