# Default values for node-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: genesis

volumes:
  jsFolder: /dist-js
  mntFolder: /mnt/js-dist
  mntType: Directory
  

nginx:
  name: nginx
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    nodePort: 30000

sidecar:
  name: sidecar
  image:
    repository: genome-sidecar
    tag: latest
    pullPolicy: IfNotPresent


modelstore:
  name: modelstore
  image:
    repository: genome-modelstore
    tag: local.1
    pullPolicy: IfNotPresent
  jsFolder: dist-js

routing:
  name: routing
  image:
    repository: genome-routing
    tag: local.1
    pullPolicy: IfNotPresent

compute:
  name: compute
  image:
    repository: genome-compute
    tag: local.1
    pullPolicy: IfNotPresent

scoring:
  name: scoring
  image:
    repository: genome-scoring
    tag: local.1
    pullPolicy: IfNotPresent

visualizer:
  name: visualizer
  image:
    repository: genome-visualizer
    tag: local.1
    pullPolicy: IfNotPresent

elastic:
  name: elastic
