# Staging values for node-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: staging

nginx:
  name: nginx
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent

modelstore:
  name: modelstore
  image:
    repository: genome-modelstore
    tag: staging
    pullPolicy: Always
  jsFolder: dist


routing:
  name: routing
  image:
    repository: genome-routing
    tag: staging
    pullPolicy: Always


compute:
  name: compute
  image:
    repository: genome-compute
    tag: staging
    pullPolicy: Always


scoring:
  name: scoring
  image:
    repository: genome-scoring
    tag: staging
    pullPolicy: Always


visualizer:
  name: visualizer
  image:
    repository: genome-visualizer
    tag: staging
    pullPolicy: Always


elastic:
  name: elastic
