FROM openjdk:8-jdk-slim
COPY --from=python:3.6 / /

#update
RUN apt-get update

#install requirements
COPY ./service-modelstore/sdk/src/python/requirements-test.txt /tmp/requirements.txt
WORKDIR /tmp
RUN pip3 install -r requirements.txt
RUN pip3 install coverage


#copy app
COPY ./service-modelstore/sdk/src/python /app
WORKDIR /

ENV MODELSTORE http://genome.ai
CMD ["coverage", "run",  "-m", "unittest", "discover", "-s", "app.test", "-p", "test_*.py", "-v"]
