FROM openjdk:8-jdk-slim
COPY --from=python:3.6 / /

#update
RUN apt-get update

#install requirements
COPY ./service-modelstore/sdk/src/python/requirements-test.txt /tmp/requirements.txt
WORKDIR /tmp
RUN pip3 install -r requirements.txt


#copy app
COPY ./service-modelstore/sdk/src/python /app
WORKDIR /

ENV MODELSTORE http://genome.ai
CMD ["python", "-m", "unittest", "discover", "app.test", "-v"]
